### ISSUE TITLE
[Suggestion] Offline open inventory

### ISSUE THREAD

**Issue by goon1214** [goon1214/jonahwill.org-server#13]
**Please describe the feature you want**
Open inventory plugin that allows addition and removal of items from inventories. **Ensure compatibility with multiverse inventories before adding to the network.**

**Comment by JayUplink** [comment]
OpenInv installed on Main, Stream & Events. Can access any player inventory, offline or online, including armour & offhand. Will be working on events on next restart. Known working with multiverse inventories.
